### ISSUE TITLE
[crash] can't download anything apparently

### ISSUE THREAD

**Issue by joex92** [aniyomiorg/aniyomi#1931]
Here's the crashlog:
![aniyomi_crash_logs.txt](https://github.com/user-attachments/files/18725153/aniyomi_crash_logs.txt)

I have about 300gb free, I set up an Aniyomi folder on the internal storage, at the beginning it was working fine, now it doesn't work and just keep crashing every time I want to download something, in this case a manga extension update...

**Comment by Secozzi** [comment]
What path do you have set as the storage location?

**Comment by joex92** [comment]
Should I use the default one on the android data folder?

**Comment by Secozzi** [comment]
It should work, can you see of you're having any issues in Mihon?

**Comment by joex92** [comment]
oh... I don't use Mihon, I'm only using their repo because it seems like it's the most updated one for Manga extensions... do you think that would be the issue?

**Comment by Secozzi** [comment]
I'm not entirely sure what's going on, but if you're getting the crash in Mihon, you should report it to them. Since we're a fork of Mihon, it'll be fixed in aniyomi eventually if Mihon fixes it.

**Comment by joex92** [comment]
oh... I thought this was a fork from the original Tachiyomi (although is dead now)... I'm going to do that then... thanks...

**Comment by fakebhai** [comment]
> got the same crash... 🤔 I actually managed to uninstall chrome and use other browser with [this tool](https://github.com/0x192/universal-android-debloater)... do you think that might be the issue? although the app has its own webview, doesn't it? I find it odd... I'm going to try restoring chrome...


yep that's likely the issue. if you read aniyomi [troubleshooting webview-update](https://aniyomi.org/docs/guides/troubleshooting/#webview-update) then u can see this written there:

- Caution with Non-Standard WebView

Using non-standard WebView (like Firefox) might cause Aniyomi to malfunction or crash.

It's best to use the standard Android System WebView or Google Chrome.

**Comment by joex92** [comment]
> > got the same crash... 🤔 I actually managed to uninstall chrome and use other browser with [this tool](https://github.com/0x192/universal-android-debloater)... do you think that might be the issue? although the app has its own webview, doesn't it? I find it odd... I'm going to try restoring chrome...
> 
> yep that's likely the issue. if you read aniyomi [troubleshooting webview-update](https://aniyomi.org/docs/guides/troubleshooting/#webview-update) then u can see this written there:
> 
> * Caution with Non-Standard WebView
> 
> Using non-standard WebView (like Firefox) might cause Aniyomi to malfunction or crash.
> 
> It's best to use the standard Android System WebView or Google Chrome.

@fakebhai it has nothing to do with chrome... and I restored Chrome and it's still not working... the app has its own webview that doesn't depend on the OS's browser...


> I'm not entirely sure what's going on, but if you're getting the crash in Mihon, you should report it to them. Since we're a fork of Mihon, it'll be fixed in aniyomi eventually if Mihon fixes it.

@Secozzi in the end seems like it's not related to the manga side, because the Anime side is getting me the same issues too... apparently it may be an issue with the latest updates on the OS, in my case I have Android 15 with HyperOS 2.0... one of the devs on Mihon is going to look into it because I'm not the only one with that problem, another user got the same crash... and it only happens with extension downloads...

**Comment by fakebhai** [comment]
> the app has its own webview that doesn't depend on the OS's browser...

no it does. it's written in documentation for a reason. go to your phone's developer settings and look for "webview implementation" or similar to that. that's the webview aniyomi/mihon will use.

**Comment by joex92** [comment]
mine says "Android System Webview", not chrome...

**Comment by fakebhai** [comment]
> mine says "Android System Webview", not chrome... even the icon shown is not chrome...

> >  "Android System WebView or Google Chrome."

iirc in some Huawei or old devices it says chrome but it's probably the same thing. not the point.

is it working after selecting it? if not you can try other android system webview canary/dev/beta

**Comment by joex92** [comment]
> > mine says "Android System Webview", not chrome... even the icon shown is not chrome...
> 
> > >  "Android System WebView or Google Chrome."
> 
> iirc in some Huawei or old devices it says chrome but it's probably the same thing. not the point.
> 
> is it working after selecting it? if not you can try other android system webview canary/dev/beta

There's only one thou

![Screenshot_2025-02-11-11-15-33-200_com.android.settings.jpg](https://github.com/user-attachments/assets/334933c1-3cdd-4464-8211-00908239f328)

**Comment by fakebhai** [comment]
> There's only one thou

hmm since it's selected it may not be webview's fault. you can try others from playstore but doubt it's gonna make any difference.

**Comment by joex92** [comment]
Seems like latest hyperos update fixed it... Weeks later after the latest update I just gave it a try and it started downloading and installing with no problem...
